apiVersion: v1
kind: Service
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: configbundle
    app.kubernetes.io/managed-by: kustomize
spec:
  type: ClusterIP
  selector:
    control-plane: controller-manager
    app.kubernetes.io/name: configbundle
  ports:
  - name: dispatch
    port: 8095
    targetPort: dispatch
    protocol: TCP
