datacenter: colo-galleon
servers:
  - serviceTag: 3RK3V64
    hostname: colo-r740-01
    oobIP: 10.10.1.45
    idracSettings:
      firmwareVersion: 7.20.10.05
      sshEnabled: true
      ipmiEnabled: false
      lockdownModeEnabled: false
      osToIdracPassThroughEnabled: false
      usbManagementPortEnabled: true
      dhcpEnabled: false
      racadmEnabled: true
  - serviceTag: 7BN2X91
    hostname: colo-r740-02
    oobIP: 10.10.1.46
    idracSettings:
      firmwareVersion: 7.20.10.05
      sshEnabled: true
      ipmiEnabled: false
      lockdownModeEnabled: false
      osToIdracPassThroughEnabled: false
      usbManagementPortEnabled: true
      dhcpEnabled: false
      racadmEnabled: true
