//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigBundle) DeepCopyInto(out *ConfigBundle) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigBundle.
func (in *ConfigBundle) DeepCopy() *ConfigBundle {
	if in == nil {
		return nil
	}
	out := new(ConfigBundle)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConfigBundle) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigBundleList) DeepCopyInto(out *ConfigBundleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ConfigBundle, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigBundleList.
func (in *ConfigBundleList) DeepCopy() *ConfigBundleList {
	if in == nil {
		return nil
	}
	out := new(ConfigBundleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConfigBundleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigBundleSpec) DeepCopyInto(out *ConfigBundleSpec) {
	*out = *in
	if in.Servers != nil {
		in, out := &in.Servers, &out.Servers
		*out = make([]ServerSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Takeover != nil {
		in, out := &in.Takeover, &out.Takeover
		*out = make([]TakeoverEntry, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigBundleSpec.
func (in *ConfigBundleSpec) DeepCopy() *ConfigBundleSpec {
	if in == nil {
		return nil
	}
	out := new(ConfigBundleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigBundleStatus) DeepCopyInto(out *ConfigBundleStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastAppliedAt != nil {
		in, out := &in.LastAppliedAt, &out.LastAppliedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigBundleStatus.
func (in *ConfigBundleStatus) DeepCopy() *ConfigBundleStatus {
	if in == nil {
		return nil
	}
	out := new(ConfigBundleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdracSpec) DeepCopyInto(out *IdracSpec) {
	*out = *in
	if in.FirmwareVersion != nil {
		in, out := &in.FirmwareVersion, &out.FirmwareVersion
		*out = new(string)
		**out = **in
	}
	if in.SSHEnabled != nil {
		in, out := &in.SSHEnabled, &out.SSHEnabled
		*out = new(bool)
		**out = **in
	}
	if in.IPMIEnabled != nil {
		in, out := &in.IPMIEnabled, &out.IPMIEnabled
		*out = new(bool)
		**out = **in
	}
	if in.LockdownModeEnabled != nil {
		in, out := &in.LockdownModeEnabled, &out.LockdownModeEnabled
		*out = new(bool)
		**out = **in
	}
	if in.OsToIdracPassThroughEnabled != nil {
		in, out := &in.OsToIdracPassThroughEnabled, &out.OsToIdracPassThroughEnabled
		*out = new(bool)
		**out = **in
	}
	if in.UsbManagementPortEnabled != nil {
		in, out := &in.UsbManagementPortEnabled, &out.UsbManagementPortEnabled
		*out = new(bool)
		**out = **in
	}
	if in.DHCPEnabled != nil {
		in, out := &in.DHCPEnabled, &out.DHCPEnabled
		*out = new(bool)
		**out = **in
	}
	if in.RacadmEnabled != nil {
		in, out := &in.RacadmEnabled, &out.RacadmEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdracSpec.
func (in *IdracSpec) DeepCopy() *IdracSpec {
	if in == nil {
		return nil
	}
	out := new(IdracSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerConfig) DeepCopyInto(out *ServerConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerConfig.
func (in *ServerConfig) DeepCopy() *ServerConfig {
	if in == nil {
		return nil
	}
	out := new(ServerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServerConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerConfigList) DeepCopyInto(out *ServerConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ServerConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerConfigList.
func (in *ServerConfigList) DeepCopy() *ServerConfigList {
	if in == nil {
		return nil
	}
	out := new(ServerConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServerConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerConfigSpec) DeepCopyInto(out *ServerConfigSpec) {
	*out = *in
	if in.Hostname != nil {
		in, out := &in.Hostname, &out.Hostname
		*out = new(string)
		**out = **in
	}
	if in.OobIP != nil {
		in, out := &in.OobIP, &out.OobIP
		*out = new(string)
		**out = **in
	}
	in.Idrac.DeepCopyInto(&out.Idrac)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerConfigSpec.
func (in *ServerConfigSpec) DeepCopy() *ServerConfigSpec {
	if in == nil {
		return nil
	}
	out := new(ServerConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerConfigStatus) DeepCopyInto(out *ServerConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerConfigStatus.
func (in *ServerConfigStatus) DeepCopy() *ServerConfigStatus {
	if in == nil {
		return nil
	}
	out := new(ServerConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerSpec) DeepCopyInto(out *ServerSpec) {
	*out = *in
	if in.Hostname != nil {
		in, out := &in.Hostname, &out.Hostname
		*out = new(string)
		**out = **in
	}
	if in.OobIP != nil {
		in, out := &in.OobIP, &out.OobIP
		*out = new(string)
		**out = **in
	}
	in.Idrac.DeepCopyInto(&out.Idrac)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerSpec.
func (in *ServerSpec) DeepCopy() *ServerSpec {
	if in == nil {
		return nil
	}
	out := new(ServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TakeoverEntry) DeepCopyInto(out *TakeoverEntry) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TakeoverEntry.
func (in *TakeoverEntry) DeepCopy() *TakeoverEntry {
	if in == nil {
		return nil
	}
	out := new(TakeoverEntry)
	in.DeepCopyInto(out)
	return out
}
