apiVersion: v1
kind: ServiceAccount
metadata:
  name: backupconfig-controller
  namespace: system
  labels:
    app.kubernetes.io/name: backupconfig-controller
    app.kubernetes.io/managed-by: kustomize
