apiVersion: v1
kind: ServiceAccount
metadata:
  name: serverconfig-controller
  namespace: system
  labels:
    app.kubernetes.io/name: serverconfig-controller
    app.kubernetes.io/managed-by: kustomize
