apiVersion: v1
kind: Service
metadata:
  name: serverconfig-controller-metrics
  namespace: system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: serverconfig-controller
    app.kubernetes.io/managed-by: kustomize
spec:
  type: ClusterIP
  selector:
    control-plane: controller-manager
    app.kubernetes.io/name: serverconfig-controller
  ports:
  - name: metrics
    port: 8093
    targetPort: metrics
    protocol: TCP
